name: docker registry login

on: [push]


jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        env:
          DOCKER_TOKEN: ${{ env.DOCKER_TOKEN }}
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
